#!/bin/bash
if [ ! -f 'dbus-core.cabal' ]; then
	echo -n "Can't find dbus-core.cabal; please run this script as"
	echo -n " ./scripts/dist from within the dbus-core source"
	echo " directory"
	exit 1
fi

. scripts/common.bash

require_anansi
require_cabal_dev

echo "Building dist for dbus-core_$VERSION using $CABAL_DEV"

rm -rf hs dist
$ANANSI --noline -o hs src/dbus-core.anansi || exit 1
$CABAL_DEV configure || exit 1
$CABAL_DEV build || exit 1
$CABAL_DEV sdist || exit 1

mv "dist/dbus-core-$VERSION.tar.gz" "./dbus-core_$VERSION.tar.gz"
ln -f "./dbus-core_$VERSION.tar.gz" "./dbus-core-$VERSION.tar.gz"
if [ -n "$XZ" ]; then
	gzip -dfc "dbus-core_$VERSION.tar.gz" > "dbus-core_$VERSION.tar"
	xz -f -C sha256 -9 "dbus-core_$VERSION.tar"
fi

if [ -n "$XELATEX" ]; then
	make_pdf
fi

echo ""
echo "============================================================"
if [ -n "$XELATEX" ]; then
	echo "  woven source        : dbus-core_$VERSION.pdf"
fi
echo "  source tarball (gz) : dbus-core_$VERSION.tar.gz"
if [ -n "$XZ" ]; then
	echo "  source archive (xz) : dbus-core_$VERSION.tar.xz"
fi
echo "============================================================"
