#!/bin/bash
if [ ! -f 'dbus-core.cabal' ]; then
	echo -n "Can't find dbus-core .cabal; please run this script as"
	echo -n " ./scripts/run-coverage from within the dbus-core source"
	echo " directory"
	exit 1
fi

. scripts/common.bash

require_anansi
require_cabal_dev

rm -rf hs dist
$ANANSI --noline -o hs src/dbus-core.anansi || exit 1
$CABAL_DEV install || exit 1

pushd tests
rm -rf dist
$CABAL_DEV -s ../cabal-dev install --flags="coverage" || exit 1
popd

rm dbus-core_tests.tix
cabal-dev/bin/dbus-core_tests

hpc markup --srcdir=hs --srcdir=tests/ dbus-core_tests.tix --destdir=hpc-markup --exclude=Main
hpc report --srcdir=hs --srcdir=tests/ dbus-core_tests.tix --exclude=Main
